export const errors =
{
    converterElementNotFound : "Aucun élément HTML n'a été trouvé ayant comme \"id\" : ",
    converterFieldNotFound : "Le champ n'existe pas dans les données ou les données n'ont pas encore été chargées.",
    converterNeedDatasElt: "Merci de fournir un id valide pour l'élément où afficher les données.",
    converterRefreshFail: "Le nom des champs et l'élement du DOM receveur sont nécessaires à l'affichage des données.",
    filterNeedDatas: "Le création d'un filtre nécessite la présence des données à filtrer.",
    needPositiveInteger: "needPositiveInteger",
    pagination2HTMLFail : "Toutes les donnée nécessaires à la création des sélecteurs de pagination n'ont pas été fournies.",
    paginationNeedByfaultValueBeInOptions: "La valeur de pagination par défaut doit faire partie des options proposées.",
    paginationNeedDatas: "Il ne peut y avoir de pagination, si les données n'ont pas été récupérées.",
    paginationNeedOptionsValues: "Vous n'avez fourni aucune options possibles pour la pagination.",
    paginationOptionsDuplicatedValues: "Une valeur en doublon a été trouvée dans les options de pagination.",
    paginationNeedPositiveInteger: "Merci de fournir un nombre entier supérieur à zéro pour désigner chaque option de pagination.",
    parserDatasNotFound : "Aucune donnée n'a été trouvée.",
    parserElementsNotFound: "Aucun élément trouvé dans le document pour le sélecteur fourni : ",
    parserFail: "La lecture des données a échoué.",
    parserFieldNameFail: "Les noms de champs fournis doivent être uniques et ne peuvent être vides.",
    parserFieldsNotFound: "Aucun nom de champs n'a été trouvé par le parseur.",
    parserLineWithoutDatas: "Une ligne ne contenant aucune donnée valide a été trouvée.",
    parserMeetErrors : "Au moins une erreur a été rencontrée durant le traitement des données.",
    parserNeedDatas: "Merci de fournir une chaîne de caractères valide à parser.",
    parserNeedSource: "Merci de fournir une chaîne de caractères où une url pour les données à parser.",
    parserNumberOfFieldsFail: "Il n'y a pas le nombre de champs attendu pour cet enregistrement.",
    parserRemoteFail: "Erreur rencontrée durant l'accès aux données distantes.",
    parserSelectorsIsEmpty: "Les sélecteurs CSS ne peuvent pas être une chaîne vide.",
    parserTypeError: "Une donnée a été trouvée avec un type imprévu : ",
    remoteSourceHeaderIsUnallowed: "Le nom d'une des entêtes passées n'est pas autorisé.", 
    remoteSourceNeedUrl: "Merci de fournir une url valide pour la source distante de données.", 
    remoteSourceUrlFail: "L'url fournie ne semble pas valide.", 
    renderNeedFields: "Les noms de champs doivent être fournis avant de demander l'affichage des données.",
    searchBtnTxtFail: "Le texte du bouton du moteur de recherche doit contenir au maximum 30 caractères.",
    searchFieldNotFound: "Au moins un des champs devant être utilisés par le moteur de recherche n'existe pas dans les données.",
    selector2HTMLFail: "Le création d'un filtre dans le DOM nécessite l'initialisation de l'élément HTML et du numéro du champs à filter.",
    selectorFieldIsEmpty: "Aucune donnée trouvée pour le champ du filtre",
    selectorFieldNotFound: "Au moins un des champs devant servir à filtrer les données n'existe pas dans le fichier.",  
    selectorSelectedIndexNotFound: "La valeur sélectionnée n'a pas été trouvée dans la liste des champs.",
    sortingFieldNeedDatas: "La création d'un  champ de classement nécessite la transmission de la liste des champs.",
    sortingFieldNotFound: "Au moins un des champs devant permettre de classer les données n'existe pas dans ceux à afficher.",
    sortingFieldsNbFail: "Le nombre de champs trouvés dans le DOM ne correspond pas à celui des données à classer.",
    sortingFieldsNotInHTML: "Les champs pouvant servir à classer les données n'ont pas été trouvés dans le DOM.",
};
